targets:
  $default:
    sources:
      - $package$
      - lib/**
      - swagger/**
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: swagger
          output_folder: lib/generated
          with_base_url: false
          separate_models: true
          include_paths:
            - '\/{version}\/sites'