targets:
  $default:
    builders:
      swagger_dart_code_generator:
        enabled: false
        options:
          input_folder: swagger
          output_folder: lib/generated
          with_base_url: false
          separate_models: true